CREATE TABLE iF NOT EXISTS BOOKS (
    ID VARCHAR(45) NOT NULL,
    TITLE TEXT NOT NULL,
    AUTHOR VARCHAR(50) NOT NULL,
    URL  VARCHAR(225) NOT NULL,
    STOCK INTEGER NOT NULL,
    AVAILABLE BOOLEAN,
    CREATED_AT VARCHAR(60) NOT NULL,
    UPDATED_AT VARCHAR(60) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE iF NOT EXISTS STUDENTS (
    ID VARCHAR(45) NOT NULL,
    USERNAME VARCHAR(20) NOT NULL,
    FIRST_NAME VARCHAR(30) NOT NULL,
    LAST_NAME VARCHAR(30) NOT NULL,
    PASSWORD VARCHAR(200) NOT NULL,
    CREATED_AT VARCHAR(60) NOT NULL,
    UPDATED_AT VARCHAR(60) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE iF NOT EXISTS BORROWED_BOOKS (
    ID VARCHAR(45) NOT NULL,
    STUDENT_ID VARCHAR(45) NOT NULL,
    BOOK_ID VARCHAR(45) NOT NULL,
    RETURNED BOOLEAN,
    CREATED_AT VARCHAR(60) NOT NULL,
    UPDATED_AT VARCHAR(60) NOT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(ID) ON DELETE CASCADE,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(ID) ON DELETE CASCADE
);